/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    projects: Project;
    services: Service;
    sectors: Sector;
    testimonials: Testimonial;
    clients: Client;
    articles: Article;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every page on the site. Stack blocks in 'Page sections' to build the layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The URL path segment. Auto-filled from the title — edit only if you must.
   */
  slug: string;
  layout?:
    | (
        | HeroBlock
        | RichTextBlock
        | StatsCountersBlock
        | ServicesGridBlock
        | SectorTilesBlock
        | ProjectsListBlock
        | ImageGalleryBlock
        | LogoWallBlock
        | TestimonialsBlock
        | StepsBlock
        | CTABandBlock
        | FAQBlock
        | CalculatorEmbedBlock
        | ContactRFQBlock
        | SpacerBlock
      )[]
    | null;
  /**
   * Search & social. Leave blank to use the site defaults.
   */
  seo?: {
    /**
     * Overrides the page/site title.
     */
    title?: string | null;
    /**
     * Canonical URL (advanced; usually leave blank).
     */
    canonical?: string | null;
    /**
     * ~150–160 characters. Shown in search results and link previews.
     */
    description?: string | null;
    /**
     * Social share image (Open Graph), 1200×630.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * Hint only — the live menu is controlled by Settings → Navigation.
   */
  showInNav?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Small label above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  subhead?: string | null;
  tone?: ('dark' | 'light') | null;
  /**
   * Optional background image.
   */
  backgroundImage?: (number | null) | Media;
  ctas?:
    | {
        label: string;
        type?: ('page' | 'custom') | null;
        /**
         * Pick a page — its URL is always kept in sync.
         */
        page?: (number | null) | Page;
        /**
         * e.g. https://… or /a/known/path
         */
        url?: string | null;
        newTab?: boolean | null;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines (required).
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  appearance?: ('default' | 'muted' | 'dark') | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsCountersBlock".
 */
export interface StatsCountersBlock {
  intro?: string | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  stats?:
    | {
        /**
         * Leave blank until the real figure is confirmed (shows a skeleton).
         */
        value?: number | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsCounters';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock".
 */
export interface ServicesGridBlock {
  heading?: string | null;
  lede?: string | null;
  source?: ('auto' | 'selected') | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  services?: (number | Service)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * The URL path segment. Auto-filled from the title — edit only if you must.
   */
  slug: string;
  icon: 'solar' | 'electrical' | 'grounding' | 'smart';
  order?: number | null;
  /**
   * One-line outcome shown on cards and grids.
   */
  summary: string;
  /**
   * Scope of work — what's included.
   */
  scope?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Standards & methodology (IEC / BNBC / NFPA references).
   */
  standards?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search & social. Leave blank to use the site defaults.
   */
  seo?: {
    /**
     * Overrides the page/site title.
     */
    title?: string | null;
    /**
     * Canonical URL (advanced; usually leave blank).
     */
    canonical?: string | null;
    /**
     * ~150–160 characters. Shown in search results and link previews.
     */
    description?: string | null;
    /**
     * Social share image (Open Graph), 1200×630.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectorTilesBlock".
 */
export interface SectorTilesBlock {
  heading?: string | null;
  lede?: string | null;
  source?: ('auto' | 'selected') | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  sectors?: (number | Sector)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectorTiles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  title: string;
  /**
   * The URL path segment. Auto-filled from the title — edit only if you must.
   */
  slug: string;
  icon: 'manufacturing' | 'power' | 'commercial' | 'ports';
  order?: number | null;
  summary: string;
  /**
   * Sector challenges → how Sustech solves them.
   */
  challenges?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Relevant services for this sector.
   */
  services?: (number | Service)[] | null;
  /**
   * Search & social. Leave blank to use the site defaults.
   */
  seo?: {
    /**
     * Overrides the page/site title.
     */
    title?: string | null;
    /**
     * Canonical URL (advanced; usually leave blank).
     */
    canonical?: string | null;
    /**
     * ~150–160 characters. Shown in search results and link previews.
     */
    description?: string | null;
    /**
     * Social share image (Open Graph), 1200×630.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsListBlock".
 */
export interface ProjectsListBlock {
  heading?: string | null;
  lede?: string | null;
  source?: ('featured' | 'selected') | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  projects?: (number | Project)[] | null;
  viewAllLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectsList';
}
/**
 * Case studies. Hermes can draft these from ERP data; an admin/editor publishes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  /**
   * The URL path segment. Auto-filled from the title — edit only if you must.
   */
  slug: string;
  sector?: (number | null) | Sector;
  year?: number | null;
  featured?: boolean | null;
  location?: string | null;
  /**
   * e.g. 2.5 MWp, 1× 2500 kVA substation.
   */
  capacity?: string | null;
  summary: string;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  outcome?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  client?: (number | null) | Client;
  /**
   * Search & social. Leave blank to use the site defaults.
   */
  seo?: {
    /**
     * Overrides the page/site title.
     */
    title?: string | null;
    /**
     * Canonical URL (advanced; usually leave blank).
     */
    canonical?: string | null;
    /**
     * ~150–160 characters. Shown in search results and link previews.
     */
    description?: string | null;
    /**
     * Social share image (Open Graph), 1200×630.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * Client logo (transparent PNG/SVG). Powers the logo wall.
   */
  logo?: (number | null) | Media;
  /**
   * Used to show relevant logos on sector pages.
   */
  sectors?: (number | Sector)[] | null;
  order?: number | null;
  /**
   * Optional link to the client's website.
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  heading?: string | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock".
 */
export interface LogoWallBlock {
  heading?: string | null;
  source?: ('auto' | 'selected') | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  clients?: (number | Client)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoWall';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  source?: ('auto' | 'selected') | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  testimonials?: (number | Testimonial)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  person: string;
  role?: string | null;
  company: string;
  /**
   * Optional company logo.
   */
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  eyebrow?: string | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  heading?: string | null;
  steps?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABandBlock".
 */
export interface CTABandBlock {
  heading: string;
  subhead?: string | null;
  ctas?:
    | {
        label: string;
        type?: ('page' | 'custom') | null;
        /**
         * Pick a page — its URL is always kept in sync.
         */
        page?: (number | null) | Page;
        /**
         * e.g. https://… or /a/known/path
         */
        url?: string | null;
        newTab?: boolean | null;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalculatorEmbedBlock".
 */
export interface CalculatorEmbedBlock {
  heading?: string | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  body?: string | null;
  tool?: ('solarcalc' | 'roi') | null;
  ctaLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'calculatorEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactRFQBlock".
 */
export interface ContactRFQBlock {
  heading?: string | null;
  appearance?: ('default' | 'muted' | 'dark') | null;
  subhead?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactRFQ';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  size?: ('sm' | 'md' | 'lg') | null;
  divider?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * Knowledge hub. Lives at /knowledge/[slug].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * The URL path segment. Auto-filled from the title — edit only if you must.
   */
  slug: string;
  author?: string | null;
  publishedDate?: string | null;
  /**
   * TL;DR / answer shown up top and in listings.
   */
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search & social. Leave blank to use the site defaults.
   */
  seo?: {
    /**
     * Overrides the page/site title.
     */
    title?: string | null;
    /**
     * Canonical URL (advanced; usually leave blank).
     */
    canonical?: string | null;
    /**
     * ~150–160 characters. Shown in search results and link previews.
     */
    description?: string | null;
    /**
     * Social share image (Open Graph), 1200×630.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Controls permissions. Only admins can change roles.
   */
  role: 'admin' | 'editor' | 'hermes';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        statsCounters?: T | StatsCountersBlockSelect<T>;
        servicesGrid?: T | ServicesGridBlockSelect<T>;
        sectorTiles?: T | SectorTilesBlockSelect<T>;
        projectsList?: T | ProjectsListBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
        logoWall?: T | LogoWallBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        ctaBand?: T | CTABandBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        calculatorEmbed?: T | CalculatorEmbedBlockSelect<T>;
        contactRFQ?: T | ContactRFQBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        canonical?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  showInNav?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subhead?: T;
  tone?: T;
  backgroundImage?: T;
  ctas?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  appearance?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsCountersBlock_select".
 */
export interface StatsCountersBlockSelect<T extends boolean = true> {
  intro?: T;
  appearance?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock_select".
 */
export interface ServicesGridBlockSelect<T extends boolean = true> {
  heading?: T;
  lede?: T;
  source?: T;
  appearance?: T;
  services?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectorTilesBlock_select".
 */
export interface SectorTilesBlockSelect<T extends boolean = true> {
  heading?: T;
  lede?: T;
  source?: T;
  appearance?: T;
  sectors?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsListBlock_select".
 */
export interface ProjectsListBlockSelect<T extends boolean = true> {
  heading?: T;
  lede?: T;
  source?: T;
  appearance?: T;
  projects?: T;
  viewAllLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock_select".
 */
export interface ImageGalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  appearance?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock_select".
 */
export interface LogoWallBlockSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  appearance?: T;
  clients?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  appearance?: T;
  testimonials?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  appearance?: T;
  heading?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABandBlock_select".
 */
export interface CTABandBlockSelect<T extends boolean = true> {
  heading?: T;
  subhead?: T;
  ctas?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  appearance?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalculatorEmbedBlock_select".
 */
export interface CalculatorEmbedBlockSelect<T extends boolean = true> {
  heading?: T;
  appearance?: T;
  body?: T;
  tool?: T;
  ctaLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactRFQBlock_select".
 */
export interface ContactRFQBlockSelect<T extends boolean = true> {
  heading?: T;
  appearance?: T;
  subhead?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock_select".
 */
export interface SpacerBlockSelect<T extends boolean = true> {
  size?: T;
  divider?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sector?: T;
  year?: T;
  featured?: T;
  location?: T;
  capacity?: T;
  summary?: T;
  challenge?: T;
  solution?: T;
  outcome?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  client?: T;
  seo?:
    | T
    | {
        title?: T;
        canonical?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  order?: T;
  summary?: T;
  scope?: T;
  standards?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        canonical?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  order?: T;
  summary?: T;
  challenges?: T;
  services?: T;
  seo?:
    | T
    | {
        title?: T;
        canonical?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  person?: T;
  role?: T;
  company?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  sectors?: T;
  order?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  publishedDate?: T;
  excerpt?: T;
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        canonical?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Logo, company details, contacts, social and SEO defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Optional — a text wordmark is used if empty.
   */
  logo?: (number | null) | Media;
  companyName: string;
  shortName?: string | null;
  tagline?: string | null;
  /**
   * Company blurb used in the footer and as an SEO fallback.
   */
  description?: string | null;
  foundingYear?: number | null;
  areaServed?: string | null;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    /**
     * ISO country code (e.g. BD).
     */
    country?: string | null;
  };
  /**
   * e.g. Sun–Thu, 9:00–18:00
   */
  hours?: string | null;
  social?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used when a page has no SEO title.
   */
  defaultTitle?: string | null;
  /**
   * %s is replaced by the page title.
   */
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  /**
   * Default social share image (1200×630).
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The header and footer menus. Add, rename, reorder or remove tabs here — no code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Top-level tabs, left to right. A tab with children becomes a dropdown.
   */
  header?:
    | {
        label: string;
        type?: ('page' | 'custom') | null;
        /**
         * Pick a page — its URL is always kept in sync.
         */
        page?: (number | null) | Page;
        /**
         * e.g. https://… or /a/known/path
         */
        url?: string | null;
        newTab?: boolean | null;
        children?:
          | {
              label: string;
              type?: ('page' | 'custom') | null;
              /**
               * Pick a page — its URL is always kept in sync.
               */
              page?: (number | null) | Page;
              /**
               * e.g. https://… or /a/known/path
               */
              url?: string | null;
              newTab?: boolean | null;
              /**
               * Optional one-line description shown in the mega-menu.
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  headerCta: {
    label: string;
    type?: ('page' | 'custom') | null;
    /**
     * Pick a page — its URL is always kept in sync.
     */
    page?: (number | null) | Page;
    /**
     * e.g. https://… or /a/known/path
     */
    url?: string | null;
    newTab?: boolean | null;
    id?: string | null;
  };
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              type?: ('page' | 'custom') | null;
              /**
               * Pick a page — its URL is always kept in sync.
               */
              page?: (number | null) | Page;
              /**
               * e.g. https://… or /a/known/path
               */
              url?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  companyName?: T;
  shortName?: T;
  tagline?: T;
  description?: T;
  foundingYear?: T;
  areaServed?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  hours?: T;
  social?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}