import "./load-env";
import { mkdirSync, writeFileSync } from "node:fs";
import { getPayload } from "payload";
import { getSource, type ImportConfig } from "../../lib/import";
import { CANONICAL_SERVICES, NEW_SERVICE_LABEL } from "../../lib/import/types";
import config from "../../payload.config";

async function main(): Promise<void> {
  const importConfig: ImportConfig = {
    source: process.env.IMPORT_SOURCE === "erp" ? "erp" : "excel",
    excelPath: process.env.DATA_FILE ?? "data/clients-pipeline.xlsx",
  };
  const source = getSource(importConfig);
  const { records, skipped, rowsRead } = await source.load();

  const payload = await getPayload({ config });

  // Resolve canonical service slugs -> existing Service doc ids.
  const services = await payload.find({ collection: "services", limit: 100, depth: 0 });
  const slugToId = new Map(services.docs.map((s) => [s.slug, s.id]));

  let created = 0;
  let updated = 0;
  const serviceMix = new Map<string, number>();
  const crosswalk: string[] = ["importKey,title,year,client"]; // gitignored de-anonymisation aid

  for (const rec of records) {
    for (const slug of rec.services) {
      const label = CANONICAL_SERVICES[slug];
      serviceMix.set(label, (serviceMix.get(label) ?? 0) + 1);
    }
    for (const p of rec.proposedServices) serviceMix.set(p, (serviceMix.get(p) ?? 0) + 1);

    const serviceIds = rec.services
      .map((slug) => slugToId.get(slug))
      .filter((id): id is number => typeof id === "number");

    const importNotes = [
      "Sector: TODO — assign before publishing.",
      rec.category ? `Category (source): ${rec.category}` : null,
      rec.rawServiceLines ? `Service lines (source): ${rec.rawServiceLines}` : null,
      rec.proposedServices.length
        ? `Proposed NEW service — flag for MD: ${rec.proposedServices.join(", ")}`
        : null,
    ]
      .filter(Boolean)
      .join("\n");

    // WEB-SAFE PAYLOAD ONLY — no client name, no financials, no contacts/addresses/paths.
    const data = {
      name: rec.title,
      slug: `draft-${rec.importKey.slice(0, 12)}`,
      year: rec.year,
      services: serviceIds,
      clientPublic: false,
      needsSectorReview: true,
      importKey: rec.importKey,
      importSource: rec.source,
      importNotes,
      _status: "draft" as const,
    };

    const existing = await payload.find({
      collection: "projects",
      where: { importKey: { equals: rec.importKey } },
      limit: 1,
      draft: true,
      overrideAccess: true,
    });

    if (existing.docs[0]) {
      await payload.update({
        collection: "projects",
        id: existing.docs[0].id,
        data,
        draft: true,
        overrideAccess: true,
      });
      updated += 1;
    } else {
      await payload.create({ collection: "projects", data, draft: true, overrideAccess: true });
      created += 1;
    }

    crosswalk.push(
      `${rec.importKey},"${rec.title}",${rec.year ?? ""},"${rec.clientName.replace(/"/g, '""')}"`,
    );
  }

  // Crosswalk: client identities stay OUT of the repo (data/ is gitignored except *.md).
  mkdirSync("data", { recursive: true });
  writeFileSync("data/import-crosswalk.csv", `${crosswalk.join("\n")}\n`, "utf8");

  // Report: counts + reasons + service labels only — no names, no money.
  const skippedByReason = new Map<string, number>();
  for (const s of skipped) skippedByReason.set(s.reason, (skippedByReason.get(s.reason) ?? 0) + 1);

  const fmt = (m: Map<string, number>) =>
    [...m.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([k, v]) => `| ${k} | ${v} |`)
      .join("\n");

  const report = `# Project Import Report

> Generated by the project importer (\`pnpm import:projects\`). Aggregate counts only —
> no client names, financials, contacts, addresses, win rates or file paths leave the workbook.

- **Source adapter:** \`${source.id}\`
- **Generated:** ${new Date().toISOString().slice(0, 10)}

## Summary

| Metric | Count |
|---|---|
| Client rows read | ${rowsRead} |
| **Eligible (won/completed)** | ${records.length} |
| Drafts created | ${created} |
| Drafts updated (re-run) | ${updated} |
| Rows skipped | ${skipped.length} |

All eligible clients are drafted as **DRAFT** Projects, de-duplicated by client, with
\`clientPublic = false\` (anonymized), \`sector = TODO\` (Hermes assigns), financials stripped,
and narratives left blank for Hermes.

## Service mix (drafted projects)

| Service | Projects |
|---|---|
${fmt(serviceMix)}

> **${NEW_SERVICE_LABEL}** is a proposed NEW service line (not one of the four) — flagged for
> the MD; it may become a fifth service. Those projects carry the note in their Import metadata.

## Rows skipped — and why

| Reason | Count |
|---|---|
${fmt(skippedByReason)}
`;

  writeFileSync("data/import-report.md", report, "utf8");

  payload.logger.info(
    `Project import (${source.id}): ${created} created, ${updated} updated, ${skipped.length} skipped. Report: data/import-report.md`,
  );
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
